"""create lottery draws table

Revision ID: 377b13f6e3b4
Revises: ccd5e9a42517
Create Date: 2026-08-09 14:02:32.290827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '377b13f6e3b4'
down_revision: Union[str, Sequence[str], None] = 'ccd5e9a42517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery_draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.String(length=50), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('main_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bonus_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'draw_date', name='uq_lottery_draw_date'),
    sa.UniqueConstraint('lottery_id', 'draw_number', name='uq_lottery_draw_number')
    )
    op.create_index(op.f('ix_lottery_draws_draw_date'), 'lottery_draws', ['draw_date'], unique=False)
    op.create_index(op.f('ix_lottery_draws_id'), 'lottery_draws', ['id'], unique=False)
    op.create_index(op.f('ix_lottery_draws_lottery_id'), 'lottery_draws', ['lottery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lottery_draws_lottery_id'), table_name='lottery_draws')
    op.drop_index(op.f('ix_lottery_draws_id'), table_name='lottery_draws')
    op.drop_index(op.f('ix_lottery_draws_draw_date'), table_name='lottery_draws')
    op.drop_table('lottery_draws')
    # ### end Alembic commands ###
